use_default_settings: true
search:
  safe_search: 0
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
server:
  secret_key: "ultrasecretkey"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: true
