[mypy]
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = True
warn_unreachable = True
warn_redundant_casts = True
no_implicit_optional = True
strict_optional = True
disable_error_code = type-abstract
enable_error_code = unused-awaitable
exclude = (^enterprise/migrations/.*)

[mypy-enterprise.tests.unit.test_auth_routes.*]
disable_error_code = union-attr

[mypy-enterprise.sync.install_gitlab_webhooks.*]
disable_error_code = redundant-cast

[mypy-openhands.memory.condenser.impl.*]
disable_error_code = override

[mypy-openhands.controller.agent]
disable_error_code = typeddict-item

[mypy-openhands.agenthub.*]
disable_error_code = unreachable

[mypy-openhands.llm.*]
# Deprecated V0 folder
disable_error_code = unreachable,assignment,arg-type

[mypy-openai.*]
follow_imports = skip
ignore_missing_imports = True
